config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => "accounts", :controllers => { registrations: "registrations" }
  get 'welcome/index'

    root 'welcome#index'

  
  resources :users

  resources :standups, :only => [:index, :create] do
    resources :items do
      get "confirm_destroy"
    end
    resources :comments, :only => [:new, :create]
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :standup

  validates :user, :presence => true
  validates :standup, :presence => true
  validates :text, :presence => true

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :standup

  scope :today_items, -> { where(:today =>  true) }
  scope :yesterday_items, -> { where(:today =>  false) }

  validates :standup, :presence => true
  validates :content, :presence => true, length: { :minimum => 5 }
  validates :today, :inclusion => { :in => [true, false] }
end

app/models/standup.rb
class Standup < ActiveRecord::Base

  has_many :items, -> { order "created_at" }, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  belongs_to :user

  validates :user, :presence => true
  validate :creation_limit, :on => :create

  private

  def creation_limit
    if user_has_standup_for_today?
      errors.add(:user, "Can only create once a day")
    end
  end

  def user_has_standup_for_today?
    Standup.where("user_id = ? AND DATE(created_at) = ?", user_id, Date.today).any?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :standups, -> { order "created_at DESC" }, :dependent => :destroy
  has_many :comments
  mount_uploader :avatar, AvatarUploader
  
  validates :username, presence: true, length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    standups_path
  end

  def after_sign_out_path_for(resource)
    welcome_index_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_standup

  def new
    @comment = @standup.comments.build
  end

  def create
    @comment = @standup.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to standups_path
    else
      render "new"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_standup
    @standup = current_user.standups.find(params[:standup_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  respond_to :html, :js

  before_action :authenticate_user!

  def new
    @standup = current_user.standups.find(params[:standup_id])
    @item = @standup.items.build
    flash[:today] = params[:type] == "today"
  end

  def create
    @standups = current_user.standups
    standup = @standups.find(params[:standup_id])
    @item = standup.items.build(item_params)
    @item.today = flash[:today]
    @item.save
  end

  def edit
    @standup = current_user.standups.find(params[:standup_id])
    @item = @standup.items.find(params[:id])
  end

  def update
    @standups = current_user.standups
    standup = @standups.find(params[:standup_id])
    @item = standup.items.find(params[:id])
    @item.update(item_params)
  end

  def confirm_destroy
    @standup = current_user.standups.find(params[:standup_id])
    @item = @standup.items.find(params[:item_id])
  end

  def destroy
    @standups = current_user.standups
    standup = @standups.find(params[:standup_id])
    @item = standup.items.find(params[:id])
    @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    standups_path
  end

  def after_update_path_for(resource)
    standups_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController

  respond_to :html, :js

  before_action :authenticate_user!

  def index
    @standups = current_user.standups
  end

  def create
    @standups = current_user.standups
    standup = @standups.build

    standup.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/standups_helper.rb
module StandupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<div>
  <h2>Write a comment: </h2>

  <%= form_for [@standup, @comment] do |f| %>
    <div id="errors">
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <%= f.text_area :text, :id => "Text" %><br>
    <%= f.submit %>
    <%= link_to "Cancel", standups_path %>
  <% end %>
</div>

app/views/items/_delete.html.erb
<div class="modal-header">
  <h3>Delete item</h3>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete item?
</div>
<div class="modal-footer">
  <%= link_to "Yes", standup_item_path(@standup, @item), :method => :delete, :remote => true, 
    :class => "btn btn-danger" %>
  <%= link_to "No", "#", :class => "btn", :data => { :dismiss => "modal" } %>
</div>

app/views/items/_form.html.erb
<div class="modal-header">
  <h3>Item</h3>
</div>
<div class="modal-body">
  <%= form_for [@standup, @item], :remote => true do |f| %>
    <ul class="item-errors"></ul>
    <%= f.text_field :content, :id => "Item" %>
    <%= f.submit %>
  <% end %>
</div>
<div class="modal-footer">
  <%= link_to "Cancel", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/items/_save.js.erb
$("ul.item-errors").html("")
<% if @item.errors.any? %>
  <% @item.errors.full_messages.each do |message| %>
    $("ul.item-errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".standup-index").html("<%= escape_javascript(render :partial => 'standups/index') %>")
  $("#standup-modal").modal("hide")
<% end %>

app/views/items/confirm_destroy.js.erb
$("#inner-standup-modal").html("<%= escape_javascript(render 'delete') %>")
$("#standup-modal").modal("show")

app/views/items/create.js.erb
<%= render "save" %>

app/views/items/destroy.js.erb
<%= render "save" %>

app/views/items/edit.js.erb
$("#inner-standup-modal").html("<%= escape_javascript(render 'form') %>")
$("#standup-modal").modal("show")

app/views/items/new.js.erb
$("#inner-standup-modal").html("<%= escape_javascript(render 'form') %>")
$("#standup-modal").modal("show")

app/views/items/update.js.erb
<%= render "save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StandupApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
      </div>
    </div>
  </div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/standups/_index.html.erb
<% @standups.each do |standup| %>

  <div>
    <div><strong><%= standup.created_at.to_date %></strong></div>

    <h4>Yesterday items:</h4>
    <div class="yesterday-item-index">
        <% standup.items.yesterday_items.each do |yesterday_item| %> 
      <div id="yesterday_item_content">- 
        <%= yesterday_item.content %>
        <%= link_to "Edit", edit_standup_item_path(standup, yesterday_item), :remote => true %> 
        <%= link_to "Delete", standup_item_confirm_destroy_path(standup, yesterday_item), 
        :remote => true %>
      </div>
        <% end %>
      </div>

    <%= link_to "New yesterday item", new_standup_item_path(standup, :type => "yesterday"), :remote => true %>

    <h4>Today items:</h4>
    <div class="today-item-index">
      <% standup.items.today_items.each do |today_item| %>
      <div id="today_item_content">- 
        <%= today_item.content %>
        <%= link_to "Edit", edit_standup_item_path(standup, today_item), :remote => true %> 
        <%= link_to "Delete", standup_item_confirm_destroy_path(standup, today_item), :remote => true %>
      </div>
      <% end %>
    </div>
    
    <%= link_to "New today item", new_standup_item_path(standup, :type => "today"), :remote => true %><br><br>
    <div id="add-comment<%= standup.id %>">
      <%= link_to "Add comment", new_standup_comment_path(standup) %><br>
    </div>
    <% standup.comments.each do |comment| %>
      <div id="comment<%= standup.id %><%= comment.id %>">
        <% if comment.user == nil %>
          <div id="comment-author"><%= comment.user.username %> says:</div>
        <% else %>
          <div id="comment-author">Some user says:</div>
        <% end %>
        <div id="comment-text"><%= comment.text %></div><br>
      </div>
    <% end %>
  </div>
<% end %>

app/views/standups/_save.js.erb
$("ul.standup-errors").html("")
<% if current_user.errors.any? %>
  <% current_user.errors.full_messages.each do |message| %>
    $("ul.standup-errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".standup-index").html("<%= escape_javascript(render 'index') %>")
  $("#standup-modal").modal("hide")
<% end %>

app/views/standups/create.js.erb
<%= render "save" %>

app/views/standups/index.html.erb
<%= image_tag current_user.avatar_url.to_s, size: "100x100" %>
<h2><%= current_user.username %>'s  Standups: </h2>

<ul class="standup-errors"></ul>

<div>
  <%= link_to "New Standup", standups_path, :method => :post, :remote => true %>
  <br>
</div>

<div class="standup-index">
  <%= render "index" %>
</div>

<br>

Signed in as <%= current_user.username %>. Not you?
<%= link_to "Edit account", edit_user_registration_path %><br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %><br>

<div id="standup-modal" class="modal fade">
  <div class="modal-dialog">

    <div id="inner-standup-modal" class="modal-content"></div>

  </div>
</div>

app/views/standups_controller/_form.html.erb
<%= form_for @standup, :html => { :class => "form-horizontal standup" } do |f| %>

    <% if @standup.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@standup.errors.count, "error") %> prohibited this standup from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @standup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@standup[:user_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            standups_path, :class => 'btn btn-default' %>

<% end %>

app/views/standups_controller/edit.html.erb
<%- model_class = Standup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/standups_controller/index.html.erb
<%- model_class = Standup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @standups.each do |standup| %>
      <tr>
        <td><%= link_to standup.id, standup_path(standup) %></td>
        <td><%= standup.user_id %></td>
        <td><%=l standup.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_standup_path(standup), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      standup_path(standup),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_standup_path,
            :class => 'btn btn-primary' %>

app/views/standups_controller/new.html.erb
<%- model_class = Standup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/standups_controller/show.html.erb
<%- model_class = Standup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @standup.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              standups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_standup_path(@standup), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              standup_path(@standup),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<div id="user_nav">
  <h1>Welcome to Standup App</h1><h3> where you sit down to standup </h3>
  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
</div>
<div></div>